use std::collections::HashSet;

use crate::bundle::{
    incremental_bundle_payload_sha256, IncrementalBundleCheckpoint, IncrementalBundleResume,
    IncrementalSyncBundle,
};
use crate::error::{SyncError, SyncResult};
use crate::message::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncTransferMode {
    CompleteState,
    PagedCommitInventory,
    IncrementalBundleV4,
}

/// 同步会话状态机。
///
/// 管理双向同步的各个阶段：
///
/// ```text
/// Idle ──► HelloWait ──► Negotiate ──► Exchange ──► Done
///              │              │            │
///              └──────────────┴────────────┘
///                         │
///                       Error
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SyncPhase {
    Idle,
    HelloWait,
    Negotiate,
    Exchange,
    Done,
}

/// 同步协商器。
///
/// 基于双方的 head 信息和已知 commit 集合，
/// 计算出需要发送和接收的 commit 列表。
pub struct SyncNegotiator {
    /// 本地设备 ID。
    device_id: String,

    /// 本方已知的所有 commit ID。
    known_commit_ids: HashSet<String>,

    /// 对方已知的 commit ID（从 Hello 获得）。
    remote_known_commit_ids: HashSet<String>,

    /// 本方与对方声明的可选协议能力。
    local_capabilities: HashSet<String>,
    remote_capabilities: HashSet<String>,

    /// 本地分支 head。
    local_heads: Vec<BranchHead>,

    /// 对方分支 head。
    remote_heads: Vec<BranchHead>,
}

impl SyncNegotiator {
    /// 创建本地协商器。
    pub fn new(
        device_id: &str,
        local_heads: Vec<BranchHead>,
        local_commit_ids: Vec<String>,
    ) -> Self {
        Self {
            device_id: device_id.to_string(),
            known_commit_ids: local_commit_ids.into_iter().collect(),
            remote_known_commit_ids: HashSet::new(),
            local_capabilities: HashSet::new(),
            remote_capabilities: HashSet::new(),
            local_heads,
            remote_heads: Vec::new(),
        }
    }

    /// Create a negotiator that advertises the complete bounded v4 contract.
    /// The Hello generated by [`local_hello`](Self::local_hello) omits the
    /// legacy known-commit vector when the remote peer also supports paging.
    pub fn new_incremental(
        device_id: &str,
        local_heads: Vec<BranchHead>,
        local_commit_ids: Vec<String>,
    ) -> SyncResult<Self> {
        let mut negotiator = Self::new(device_id, local_heads, local_commit_ids);
        negotiator.enable_incremental_capabilities()?;
        Ok(negotiator)
    }

    pub fn enable_incremental_capabilities(&mut self) -> SyncResult<()> {
        for capability in INCREMENTAL_SYNC_CAPABILITIES {
            self.enable_capability(capability)?;
        }
        Ok(())
    }

    /// Build the local Hello. New peers do not put an unbounded commit-ID
    /// inventory in this message once paging is enabled locally.
    pub fn local_hello(&self) -> SyncResult<HelloRequest> {
        let known_commit_ids = if self
            .local_capabilities
            .contains(CAPABILITY_COMMIT_INVENTORY_PAGING_V1)
        {
            Vec::new()
        } else {
            self.known_commit_ids.iter().cloned().collect()
        };
        HelloRequest::new(&self.device_id, self.local_heads.clone(), known_commit_ids)
            .with_capabilities(self.local_capabilities.iter().cloned().collect())
    }

    /// 处理对方的 Hello 消息并生成己方的 Hello 响应。
    pub fn on_hello(&mut self, hello: &HelloRequest) -> SyncResult<HelloResponse> {
        if hello.protocol_version != PROTOCOL_VERSION {
            return Err(SyncError::VersionMismatch {
                local: PROTOCOL_VERSION,
                remote: hello.protocol_version,
            });
        }
        validate_capabilities(&hello.capabilities)?;

        self.remote_heads = hello.heads.clone();
        self.remote_known_commit_ids = hello.known_commit_ids.iter().cloned().collect();

        self.remote_capabilities = hello.capabilities.iter().cloned().collect();
        let negotiated = self
            .local_capabilities
            .intersection(&self.remote_capabilities)
            .cloned()
            .collect::<Vec<_>>();

        let known_commit_ids =
            if self.capability_is_negotiated(CAPABILITY_COMMIT_INVENTORY_PAGING_V1) {
                Vec::new()
            } else {
                self.known_commit_ids.iter().cloned().collect()
            };
        HelloResponse::new(&self.device_id, self.local_heads.clone(), known_commit_ids)
            .with_capabilities(negotiated)
    }

    /// 处理对方的 Hello 响应。
    pub fn on_hello_ack(&mut self, response: &HelloResponse) -> SyncResult<()> {
        if response.protocol_version != PROTOCOL_VERSION {
            return Err(SyncError::VersionMismatch {
                local: PROTOCOL_VERSION,
                remote: response.protocol_version,
            });
        }
        validate_capabilities(&response.capabilities)?;

        self.remote_heads = response.heads.clone();
        self.remote_known_commit_ids = response.known_commit_ids.iter().cloned().collect();
        self.remote_capabilities = response.capabilities.iter().cloned().collect();
        Ok(())
    }

    /// 计算我方需要从对方拉取的 commit ID。
    ///
    /// 即：对方有而我们没有的 commit。
    pub fn compute_want(&self, remote_commit_ids: &[String]) -> Vec<String> {
        remote_commit_ids
            .iter()
            .filter(|id| !self.known_commit_ids.contains(*id))
            .cloned()
            .collect()
    }

    /// 计算我方需要推送给对方的 commit ID。
    ///
    /// 即：我们有而对方没有的 commit。
    pub fn compute_push(&self, our_extra_ids: &[String]) -> Vec<String> {
        our_extra_ids
            .iter()
            .filter(|id| !self.remote_known_commit_ids.contains(*id))
            .cloned()
            .collect()
    }

    /// 检查双方 head 是否已经一致（无需同步）。
    pub fn is_already_synced(&self) -> bool {
        if self.local_heads.len() != self.remote_heads.len() {
            return false;
        }

        for local in &self.local_heads {
            let remote_match = self.remote_heads.iter().any(|r| {
                same_branch_identity(r, local) && r.head_commit_id == local.head_commit_id
            });
            if !remote_match {
                return false;
            }
        }
        true
    }

    /// 找出对方领先于我们的分支。
    pub fn ahead_branches(&self) -> Vec<&BranchHead> {
        self.remote_heads
            .iter()
            .filter(|remote| {
                !self.local_heads.iter().any(|local| {
                    same_branch_identity(local, remote)
                        && local.head_commit_id == remote.head_commit_id
                })
            })
            .collect()
    }

    // -- accessors --

    pub fn device_id(&self) -> &str {
        &self.device_id
    }

    pub fn local_heads(&self) -> &[BranchHead] {
        &self.local_heads
    }

    pub fn remote_heads(&self) -> &[BranchHead] {
        &self.remote_heads
    }

    pub fn known_commit_ids(&self) -> &HashSet<String> {
        &self.known_commit_ids
    }

    pub fn remote_known_commit_ids(&self) -> &HashSet<String> {
        &self.remote_known_commit_ids
    }

    pub fn enable_capability(&mut self, capability: &str) -> SyncResult<()> {
        let candidate = vec![capability.to_string()];
        validate_capabilities(&candidate)?;
        if self.local_capabilities.len() >= MAX_SYNC_CAPABILITIES
            && !self.local_capabilities.contains(capability)
        {
            return Err(SyncError::InvalidMessage(format!(
                "sync capability list exceeds {MAX_SYNC_CAPABILITIES} items"
            )));
        }
        self.local_capabilities.insert(capability.to_string());
        Ok(())
    }

    pub fn local_capabilities(&self) -> &HashSet<String> {
        &self.local_capabilities
    }

    pub fn remote_capabilities(&self) -> &HashSet<String> {
        &self.remote_capabilities
    }

    pub fn capability_is_negotiated(&self, capability: &str) -> bool {
        self.local_capabilities.contains(capability)
            && self.remote_capabilities.contains(capability)
    }

    pub fn transfer_mode(&self) -> SyncTransferMode {
        if INCREMENTAL_SYNC_CAPABILITIES
            .iter()
            .all(|capability| self.capability_is_negotiated(capability))
        {
            SyncTransferMode::IncrementalBundleV4
        } else if self.capability_is_negotiated(CAPABILITY_COMMIT_INVENTORY_PAGING_V1) {
            SyncTransferMode::PagedCommitInventory
        } else {
            SyncTransferMode::CompleteState
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SyncClientPhase {
    Idle,
    HelloSent,
    Negotiated,
    AwaitingSegmentAcknowledgement,
    Complete,
    Fallback,
}

/// Transport-neutral state holder for a negotiated synchronization exchange.
///
/// Storage adapters call [`acknowledge_incremental_segment`](Self::acknowledge_incremental_segment)
/// only after the segment has been durably applied. Merely receiving or
/// validating a bundle never advances the checkpoint.
pub struct SyncClient {
    negotiator: SyncNegotiator,
    phase: SyncClientPhase,
    mode: SyncTransferMode,
    checkpoint: Option<IncrementalBundleCheckpoint>,
    resume: Option<IncrementalBundleResume>,
}

impl SyncClient {
    pub fn new(
        negotiator: SyncNegotiator,
        checkpoint: Option<IncrementalBundleCheckpoint>,
        resume: Option<IncrementalBundleResume>,
    ) -> Self {
        Self {
            negotiator,
            phase: SyncClientPhase::Idle,
            mode: SyncTransferMode::CompleteState,
            checkpoint,
            resume,
        }
    }

    pub fn hello(&mut self) -> SyncResult<HelloRequest> {
        self.phase = SyncClientPhase::HelloSent;
        self.negotiator.local_hello()
    }

    pub fn on_hello(&mut self, hello: &HelloRequest) -> SyncResult<HelloResponse> {
        let response = self.negotiator.on_hello(hello)?;
        self.mode = self.negotiator.transfer_mode();
        self.phase = SyncClientPhase::Negotiated;
        Ok(response)
    }

    pub fn on_hello_ack(&mut self, response: &HelloResponse) -> SyncResult<()> {
        self.negotiator.on_hello_ack(response)?;
        self.mode = self.negotiator.transfer_mode();
        self.phase = SyncClientPhase::Negotiated;
        Ok(())
    }

    pub fn negotiator(&self) -> &SyncNegotiator {
        &self.negotiator
    }

    pub fn phase(&self) -> &SyncClientPhase {
        &self.phase
    }

    pub fn transfer_mode(&self) -> SyncTransferMode {
        self.mode
    }

    pub fn checkpoint(&self) -> Option<&IncrementalBundleCheckpoint> {
        self.checkpoint.as_ref()
    }

    pub fn resume(&self) -> Option<&IncrementalBundleResume> {
        self.resume.as_ref()
    }

    /// Record a completed complete-state bootstrap. The storage adapter must
    /// call this only after the bootstrap transaction is durable.
    pub fn acknowledge_complete_bootstrap(
        &mut self,
        checkpoint: IncrementalBundleCheckpoint,
    ) -> SyncResult<()> {
        if checkpoint.commit_inventory.is_none() || checkpoint.delta_inventory.is_none() {
            return Err(SyncError::InvalidMessage(
                "bootstrap acknowledgement requires a paired checkpoint".to_string(),
            ));
        }
        self.checkpoint = Some(checkpoint);
        self.resume = None;
        self.phase = SyncClientPhase::Negotiated;
        Ok(())
    }

    pub fn commit_inventory_request(
        &self,
        cursor: Option<String>,
        page_size: usize,
    ) -> SyncResult<CommitInventoryPageRequest> {
        if self.transfer_mode() == SyncTransferMode::CompleteState {
            return Err(SyncError::InvalidMessage(
                "peer did not negotiate commit inventory paging".to_string(),
            ));
        }
        CommitInventoryPageRequest::new(
            self.checkpoint
                .as_ref()
                .and_then(|checkpoint| checkpoint.commit_inventory.clone()),
            cursor,
            page_size,
        )
    }

    pub fn delta_inventory_request(
        &self,
        cursor: Option<String>,
        page_size: usize,
    ) -> SyncResult<DeltaInventoryPageRequest> {
        if self.transfer_mode() != SyncTransferMode::IncrementalBundleV4 {
            return Err(SyncError::InvalidMessage(
                "peer did not negotiate the complete delta inventory contract".to_string(),
            ));
        }
        DeltaInventoryPageRequest::new(
            self.checkpoint
                .as_ref()
                .and_then(|checkpoint| checkpoint.delta_inventory.clone()),
            cursor,
            page_size,
        )
    }

    pub fn validate_incremental_segment(
        &mut self,
        bundle: &IncrementalSyncBundle,
    ) -> SyncResult<()> {
        if self.transfer_mode() != SyncTransferMode::IncrementalBundleV4 {
            return Err(SyncError::InvalidMessage(
                "peer did not negotiate incremental bundle v4".to_string(),
            ));
        }
        let expected_base = self.checkpoint.as_ref().ok_or_else(|| {
            SyncError::InvalidMessage("incremental client has no bootstrap checkpoint".to_string())
        })?;
        bundle.validate()?;
        if &bundle.manifest.base != expected_base {
            return Err(SyncError::InvalidMessage(
                "incremental segment base does not match the client checkpoint".to_string(),
            ));
        }
        match self.resume.as_ref() {
            Some(resume)
                if resume.transfer_id == bundle.manifest.transfer_id
                    && resume.next_segment_index == bundle.manifest.segment_index
                    && bundle.manifest.previous_segment_sha256.as_deref()
                        == Some(resume.previous_segment_sha256.as_slice()) => {}
            Some(_) => {
                return Err(SyncError::InvalidMessage(
                    "incremental segment does not match the saved transfer resume state"
                        .to_string(),
                ))
            }
            None if bundle.manifest.segment_index == 0
                && bundle.manifest.previous_segment_sha256.is_none() => {}
            None => {
                return Err(SyncError::InvalidMessage(
                    "incremental segment requires resume state".to_string(),
                ))
            }
        }
        self.phase = SyncClientPhase::AwaitingSegmentAcknowledgement;
        Ok(())
    }

    /// Advance memory state after the storage adapter reports durable apply.
    pub fn acknowledge_incremental_segment(
        &mut self,
        bundle: &IncrementalSyncBundle,
    ) -> SyncResult<()> {
        self.validate_incremental_segment(bundle)?;
        self.checkpoint = Some(bundle.manifest.result.clone());
        self.resume = if bundle.manifest.is_last {
            self.phase = SyncClientPhase::Complete;
            None
        } else {
            Some(IncrementalBundleResume {
                transfer_id: bundle.manifest.transfer_id.clone(),
                next_segment_index: bundle.manifest.segment_index.checked_add(1).ok_or_else(
                    || SyncError::InvalidMessage("segment index overflow".to_string()),
                )?,
                previous_segment_sha256: incremental_bundle_payload_sha256(bundle)?,
            })
        };
        Ok(())
    }

    pub fn fallback_to_complete_state(&mut self) {
        self.mode = SyncTransferMode::CompleteState;
        self.phase = SyncClientPhase::Fallback;
        self.resume = None;
    }
}

fn same_branch_identity(left: &BranchHead, right: &BranchHead) -> bool {
    match (left.branch_id.as_deref(), right.branch_id.as_deref()) {
        (Some(left), Some(right)) => left == right,
        _ => left.branch_name == right.branch_name,
    }
}

/// Commit 包构建器。
///
/// 将 commit 列表打包成适合传输的批次。
pub struct BatchBuilder {
    max_per_batch: usize,
}

impl BatchBuilder {
    pub fn new(max_per_batch: usize) -> Self {
        Self {
            max_per_batch: max_per_batch.max(1),
        }
    }

    /// 将 commit 列表拆分为多个批次。
    pub fn build_batches(&self, commits: Vec<SerializedCommit>) -> Vec<CommitBatch> {
        let total = commits.len();
        let batch_count = total.div_ceil(self.max_per_batch);

        commits
            .chunks(self.max_per_batch)
            .enumerate()
            .map(|(i, chunk)| {
                CommitBatch::new(chunk.to_vec(), i as u32, i == batch_count.saturating_sub(1))
            })
            .collect()
    }
}

impl Default for BatchBuilder {
    fn default() -> Self {
        Self {
            max_per_batch: MAX_COMMITS_PER_BATCH,
        }
    }
}

// ---------------------------------------------------------------------------
// 测试
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bundle::{
        IncrementalBundleManifest, IncrementalSyncBundle, INCREMENTAL_BUNDLE_FORMAT,
    };

    fn make_head(branch: &str, commit: &str) -> BranchHead {
        BranchHead {
            branch_id: None,
            branch_name: branch.to_string(),
            head_commit_id: commit.to_string(),
        }
    }

    fn make_head_with_id(branch_id: &str, branch: &str, commit: &str) -> BranchHead {
        BranchHead {
            branch_id: Some(branch_id.to_string()),
            branch_name: branch.to_string(),
            head_commit_id: commit.to_string(),
        }
    }

    #[test]
    fn test_already_synced() {
        let heads = vec![make_head("main", "abc123")];
        let mut negotiator = SyncNegotiator::new("device-a", heads.clone(), vec!["abc123".into()]);

        let hello = HelloRequest::new("device-b", heads.clone(), vec!["abc123".into()]);
        negotiator.on_hello(&hello).unwrap();

        assert!(negotiator.is_already_synced());
    }

    #[test]
    fn test_not_synced_different_head() {
        let local_heads = vec![make_head("main", "abc123")];
        let remote_heads = vec![make_head("main", "def456")];

        let mut negotiator = SyncNegotiator::new("device-a", local_heads, vec!["abc123".into()]);

        let hello = HelloRequest::new(
            "device-b",
            remote_heads,
            ["abc123", "def456"].iter().map(|s| s.to_string()).collect(),
        );
        negotiator.on_hello(&hello).unwrap();

        assert!(!negotiator.is_already_synced());
        let ahead = negotiator.ahead_branches();
        assert_eq!(ahead.len(), 1);
        assert_eq!(ahead[0].head_commit_id, "def456");
    }

    #[test]
    fn branch_id_survives_display_name_changes() {
        let local_heads = vec![make_head_with_id("branch-1", "main", "abc123")];
        let remote_heads = vec![make_head_with_id("branch-1", "renamed", "abc123")];
        let mut negotiator = SyncNegotiator::new("device-a", local_heads, vec!["abc123".into()]);
        let hello = HelloRequest::new("device-b", remote_heads, vec!["abc123".into()]);
        negotiator.on_hello(&hello).unwrap();

        assert!(negotiator.is_already_synced());
        assert!(negotiator.ahead_branches().is_empty());
    }

    #[test]
    fn duplicate_names_with_different_ids_are_distinct_branches() {
        let local_heads = vec![make_head_with_id("branch-1", "review", "abc123")];
        let remote_heads = vec![make_head_with_id("branch-2", "review", "abc123")];
        let mut negotiator = SyncNegotiator::new("device-a", local_heads, vec!["abc123".into()]);
        let hello = HelloRequest::new("device-b", remote_heads, vec!["abc123".into()]);
        negotiator.on_hello(&hello).unwrap();

        assert!(!negotiator.is_already_synced());
        assert_eq!(negotiator.ahead_branches().len(), 1);
    }

    #[test]
    fn test_version_mismatch() {
        let heads = vec![make_head("main", "abc")];
        let mut negotiator = SyncNegotiator::new("device-a", heads, vec!["abc".into()]);

        let mut hello = HelloRequest::new("device-b", vec![], vec![]);
        hello.protocol_version = 999;

        let result = negotiator.on_hello(&hello);
        assert!(matches!(result, Err(SyncError::VersionMismatch { .. })));
    }

    #[test]
    fn inventory_paging_is_enabled_only_when_both_peers_advertise_it() {
        let mut responder = SyncNegotiator::new("device-a", Vec::new(), Vec::new());
        responder
            .enable_capability(CAPABILITY_COMMIT_INVENTORY_PAGING_V1)
            .unwrap();
        let hello = HelloRequest::new("device-b", Vec::new(), Vec::new())
            .with_capabilities(vec![CAPABILITY_COMMIT_INVENTORY_PAGING_V1.to_string()])
            .unwrap();

        let response = responder.on_hello(&hello).unwrap();

        assert!(response.supports(CAPABILITY_COMMIT_INVENTORY_PAGING_V1));
        assert!(responder.capability_is_negotiated(CAPABILITY_COMMIT_INVENTORY_PAGING_V1));

        let mut initiator = SyncNegotiator::new("device-b", Vec::new(), Vec::new());
        initiator
            .enable_capability(CAPABILITY_COMMIT_INVENTORY_PAGING_V1)
            .unwrap();
        initiator.on_hello_ack(&response).unwrap();
        assert!(initiator.capability_is_negotiated(CAPABILITY_COMMIT_INVENTORY_PAGING_V1));

        let legacy_hello = HelloRequest::new("legacy", Vec::new(), Vec::new());
        let legacy_response = responder.on_hello(&legacy_hello).unwrap();
        assert!(legacy_response.capabilities.is_empty());
        assert!(!responder.capability_is_negotiated(CAPABILITY_COMMIT_INVENTORY_PAGING_V1));
    }

    #[test]
    fn test_compute_want() {
        let negotiator = SyncNegotiator::new(
            "device-a",
            vec![],
            ["a", "b", "c"].iter().map(|s| s.to_string()).collect(),
        );

        let want = negotiator.compute_want(&["a".into(), "d".into(), "e".into()]);
        assert_eq!(want, vec!["d", "e"]);
    }

    #[test]
    fn test_compute_push() {
        let mut negotiator = SyncNegotiator::new(
            "device-a",
            vec![],
            ["a", "b", "c"].iter().map(|s| s.to_string()).collect(),
        );

        let hello = HelloRequest::new("device-b", vec![], vec!["a".to_string(), "d".to_string()]);
        negotiator.on_hello(&hello).unwrap();

        let push = negotiator.compute_push(&["a".to_string(), "b".to_string(), "c".to_string()]);
        assert_eq!(push, vec!["b", "c"]);
    }

    #[test]
    fn test_batch_builder_single_batch() {
        let builder = BatchBuilder::new(256);
        let commits = vec![SerializedCommit {
            commit: mdbx_core::model::Commit {
                commit_id: "c1".into(),
                device_id: "d1".into(),
                local_seq: 1,
                commit_kind: mdbx_core::model::CommitKind::Change,
                change_scope: mdbx_core::model::ChangeScope::Entry,
                changed_object_ids_ct: vec![],
                vector_clock: "{}".into(),
                message_ct: None,
                created_at: "2024-01-01T00:00:00Z".into(),
                integrity_tag: vec![],
            },
            operation: None,
            parent_ids: vec![],
            tombstones: vec![],
            object_payloads: vec![],
        }];

        let batches = builder.build_batches(commits);
        assert_eq!(batches.len(), 1);
        assert!(batches[0].is_last);
        assert_eq!(batches[0].batch_index, 0);
    }

    #[test]
    fn test_batch_builder_multiple() {
        let builder = BatchBuilder::new(2);
        let mut commits = Vec::new();
        for i in 0..5 {
            commits.push(SerializedCommit {
                commit: mdbx_core::model::Commit {
                    commit_id: format!("c{}", i),
                    device_id: "d1".into(),
                    local_seq: i,
                    commit_kind: mdbx_core::model::CommitKind::Change,
                    change_scope: mdbx_core::model::ChangeScope::Entry,
                    changed_object_ids_ct: vec![],
                    vector_clock: "{}".into(),
                    message_ct: None,
                    created_at: "2024-01-01T00:00:00Z".into(),
                    integrity_tag: vec![],
                },
                operation: None,
                parent_ids: vec![],
                tombstones: vec![],
                object_payloads: vec![],
            });
        }

        let batches = builder.build_batches(commits);
        assert_eq!(batches.len(), 3);
        assert_eq!(batches[0].batch_index, 0);
        assert!(!batches[0].is_last);
        assert_eq!(batches[1].batch_index, 1);
        assert!(!batches[1].is_last);
        assert_eq!(batches[2].batch_index, 2);
        assert!(batches[2].is_last);
    }

    #[test]
    fn test_batch_builder_zero_limit_uses_safe_minimum() {
        let builder = BatchBuilder::new(0);
        assert_eq!(builder.max_per_batch, 1);
    }

    #[test]
    fn test_syncmessage_roundtrip() {
        let msg = SyncMessage::Hello(HelloRequest::new(
            "device-1",
            vec![make_head("main", "abc123")],
            vec!["abc123".into()],
        ));

        let bytes = msg.to_bytes().unwrap();
        let restored = SyncMessage::from_bytes(&bytes).unwrap();

        match restored {
            SyncMessage::Hello(h) => {
                assert_eq!(h.device_id, "device-1");
                assert_eq!(h.heads.len(), 1);
            }
            _ => panic!("expected Hello"),
        }
    }

    #[test]
    fn incremental_capability_negotiation_omits_legacy_known_ids() {
        let local = SyncNegotiator::new_incremental(
            "device-a",
            vec![make_head("main", "local")],
            (0..10).map(|index| format!("commit-{index}")).collect(),
        )
        .unwrap();
        let hello = local.local_hello().unwrap();
        assert!(hello.known_commit_ids.is_empty());

        let mut remote = SyncNegotiator::new_incremental("device-b", vec![], vec![]).unwrap();
        let response = remote.on_hello(&hello).unwrap();
        assert!(response.known_commit_ids.is_empty());
        assert_eq!(
            remote.transfer_mode(),
            SyncTransferMode::IncrementalBundleV4
        );
    }

    #[test]
    fn old_peer_gets_legacy_known_ids_and_complete_fallback() {
        let mut local =
            SyncNegotiator::new_incremental("device-a", vec![], vec!["commit-1".to_string()])
                .unwrap();
        let legacy = HelloRequest::new("legacy", vec![], vec!["legacy-1".to_string()]);
        let response = local.on_hello(&legacy).unwrap();
        assert_eq!(response.known_commit_ids, vec!["commit-1"]);
        assert_eq!(local.transfer_mode(), SyncTransferMode::CompleteState);
    }

    #[test]
    fn delta_inventory_messages_are_bounded_and_roundtrip() {
        let request = DeltaInventoryPageRequest::new(Some("base".into()), None, 32).unwrap();
        let message = SyncMessage::DeltaInventoryPageRequest(request.clone());
        let restored = SyncMessage::from_bytes(&message.to_bytes().unwrap()).unwrap();
        match restored {
            SyncMessage::DeltaInventoryPageRequest(restored) => assert_eq!(restored, request),
            _ => panic!("expected delta inventory request"),
        }

        let response = DeltaInventoryPageResponse::new(
            vec![DeltaInventoryEntry {
                batch_seq: 1,
                batch_id: "batch-1".into(),
                batch_kind: DeltaInventoryKind::Auxiliary,
            }],
            None,
            "watermark".into(),
        )
        .unwrap();
        let message = SyncMessage::DeltaInventoryPageResponse(response.clone());
        let restored = SyncMessage::from_bytes(&message.to_bytes().unwrap()).unwrap();
        match restored {
            SyncMessage::DeltaInventoryPageResponse(restored) => assert_eq!(restored, response),
            _ => panic!("expected delta inventory response"),
        }
    }

    #[test]
    fn client_advances_checkpoint_only_after_segment_acknowledgement() {
        let negotiator = SyncNegotiator::new_incremental("device-a", vec![], vec![]).unwrap();
        let base = IncrementalBundleCheckpoint {
            commit_inventory: Some("base-commit".into()),
            delta_inventory: Some("base-delta".into()),
        };
        let result = IncrementalBundleCheckpoint {
            commit_inventory: Some("result-commit".into()),
            delta_inventory: Some("result-delta".into()),
        };
        let mut client = SyncClient::new(negotiator, Some(base.clone()), None);
        let hello = client.hello().unwrap();
        let mut peer = SyncNegotiator::new_incremental("device-b", vec![], vec![]).unwrap();
        let ack = peer.on_hello(&hello).unwrap();
        client.on_hello_ack(&ack).unwrap();
        let commit_request = client
            .commit_inventory_request(Some("commit-cursor".into()), 64)
            .unwrap();
        assert_eq!(commit_request.checkpoint.as_deref(), Some("base-commit"));
        assert_eq!(commit_request.cursor.as_deref(), Some("commit-cursor"));
        let delta_request = client
            .delta_inventory_request(Some("delta-cursor".into()), 64)
            .unwrap();
        assert_eq!(delta_request.checkpoint.as_deref(), Some("base-delta"));
        assert_eq!(delta_request.cursor.as_deref(), Some("delta-cursor"));
        let bundle = IncrementalSyncBundle {
            manifest: IncrementalBundleManifest {
                format: INCREMENTAL_BUNDLE_FORMAT.to_string(),
                vault_id: "vault-1".into(),
                source_device_id: "device-b".into(),
                exported_at: "2026-07-21T00:00:00Z".into(),
                transfer_id: "transfer-1".into(),
                segment_index: 0,
                previous_segment_sha256: None,
                is_last: true,
                base,
                result,
                commit_inventory: vec![],
                delta_inventory: vec![],
            },
            commits: vec![],
            auxiliary_deltas: vec![],
        };
        client.validate_incremental_segment(&bundle).unwrap();
        assert_eq!(
            client.phase(),
            &SyncClientPhase::AwaitingSegmentAcknowledgement
        );
        assert_eq!(
            client.checkpoint().unwrap().commit_inventory.as_deref(),
            Some("base-commit")
        );
        client.acknowledge_incremental_segment(&bundle).unwrap();
        assert_eq!(client.phase(), &SyncClientPhase::Complete);
        assert_eq!(
            client.checkpoint().unwrap().commit_inventory.as_deref(),
            Some("result-commit")
        );
        assert!(client.resume().is_none());
    }

    #[test]
    fn client_requires_paired_checkpoint_when_bootstrap_is_acknowledged() {
        let negotiator = SyncNegotiator::new_incremental("device-a", vec![], vec![]).unwrap();
        let mut client = SyncClient::new(negotiator, None, None);
        let error = client
            .acknowledge_complete_bootstrap(IncrementalBundleCheckpoint {
                commit_inventory: Some("commit-only".into()),
                delta_inventory: None,
            })
            .unwrap_err();
        assert!(error.to_string().contains("paired checkpoint"));
        assert!(client.checkpoint().is_none());
    }

    #[test]
    fn client_fallback_overrides_negotiated_incremental_mode() {
        let local = SyncNegotiator::new_incremental("device-a", vec![], vec![]).unwrap();
        let mut client = SyncClient::new(local, None, None);
        let hello = client.hello().unwrap();
        let mut peer = SyncNegotiator::new_incremental("device-b", vec![], vec![]).unwrap();
        let ack = peer.on_hello(&hello).unwrap();
        client.on_hello_ack(&ack).unwrap();
        assert_eq!(
            client.transfer_mode(),
            SyncTransferMode::IncrementalBundleV4
        );
        client.fallback_to_complete_state();
        assert_eq!(client.transfer_mode(), SyncTransferMode::CompleteState);
    }
}
